import { ProviderEnum } from "@/api/services/llmModelService";

export const LLM_PROVIDERS = [
  {
    model: ProviderEnum.OPENAI,
    name: 'OpenAI',
    chatModels: ['gpt-3.5-turbo', 'gpt-4', 'gpt-4-32k', 'gpt-4-turbo', 'gpt-4o'],
    embeddingModels: ['text-embedding-3-small', 'text-embedding-3-large', 'text-embedding-ada-002'],
    imageModels: ['dall-e-2', 'dall-e-3'],
  },
  {
    model: ProviderEnum.Q_FAN,
    name: '百度千帆',
    chatModels: [
      'ernie-4.0-turbo-8k',
      'ernie-4.0-8k',
      'ernie-3.5-8k',
      'ernie-3.5-128k',
      'ernie-speed-8k',
      'ernie-speed-128k',
      'ernie-lite-8k',
    ],
    embeddingModels: ['embedding-3', 'bge-large-zh'],
  },
  {
    model: ProviderEnum.Q_WEN,
    name: '阿里百炼',
    chatModels: [
      'qwen-turbo',
      'qwen-plus',
      'qwen-max',
      'qwen-max-longcontext',
      'qwen-7b-chat',
      'qwen-14b-chat',
      'qwen-72b-chat',
    ],
    embeddingModels: ['text-embedding-v3'],
  },
  {
    model: ProviderEnum.ZHIPU,
    name: '智谱清言',
    chatModels: [
      'glm-4',
      'glm-4v',
      'glm-4-air',
      'glm-4-airx',
      'glm-4-flash',
      'glm-3-turbo',
      'chatglm_turbo',
    ],
    embeddingModels: ['embedding-2', 'embedding-3'],
    imageModels: ['cogview-3'],
  },
  {
    model: ProviderEnum.GITEEAI,
    name: 'Gitee AI',
    chatModels: [
      'Qwen2-72B-Instruct',
      'Qwen2-7B-Instruct',
      'Qwen2.5-72B-Instruct',
      'glm-4-9b-chat',
      'deepseek-coder-33B-instruct',
      'codegeex4-all-9b',
      'Yi-34B-Chat',
      'code-raccoon-v1',
      'Qwen2.5-Coder-32B-Instruct',
    ],
  },
  {
    model: ProviderEnum.DEEPSEEK,
    name: 'DeepSeek',
    chatModels: ['deepseek-chat', 'deepseek-coder'],
  },
  {
    model: ProviderEnum.DOUYIN,
    name: '抖音豆包',
    chatModels: [],
    embeddingModels: ['text-240715', 'text-240515'],
  },
  {
    model: ProviderEnum.SILICON,
    name: '硅基流动',
    chatModels: [
      'deepseek-ai/DeepSeek-V2-Chat',
      'deepseek-ai/DeepSeek-Coder-V2-Instruct',
      'deepseek-ai/DeepSeek-V2.5',
      'Qwen/Qwen2.5-72B-Instruct-128K',
      'Qwen/Qwen2.5-72B-Instruct',
      'Qwen/Qwen2-VL-72B-Instruct',
      'Qwen/Qwen2.5-32B-Instruct',
      'Qwen/Qwen2.5-14B-Instruct',
      'Qwen/Qwen2.5-7B-Instruct',
      'Qwen/Qwen2.5-Math-72B-Instruct',
      'Qwen/Qwen2.5-Coder-7B-Instruct',
      'Qwen/Qwen2-72B-Instruct',
      'Qwen/Qwen2-7B-Instruct',
      'Qwen/Qwen2-1.5B-Instruct',
      'Qwen/Qwen2-57B-A14B-Instruct',
      'TeleAI/TeleChat2',
      '01-ai/Yi-1.5-34B-Chat-16K',
      '01-ai/Yi-1.5-9B-Chat-16K',
      '01-ai/Yi-1.5-6B-Chat',
      'THUDM/chatglm3-6b',
      'THUDM/glm-4-9b-chat',
    ],
  },
  {
    model: ProviderEnum.YI,
    name: '零一万物',
    chatModels: [
      'yi-lightning',
      'yi-large',
      'yi-medium',
      'yi-medium-200k',
      'yi-spark',
      'yi-large-rag',
      'yi-large-turbo',
    ],
  },
  {
    model: ProviderEnum.SPARK,
    name: '讯飞星火',
    chatModels: [
      { label: 'Spark Lite', value: 'lite' },
      { label: 'Spark Pro', value: 'generalv3' },
      { label: 'Spark Pro-128K', value: 'pro-128k' },
      { label: 'Spark Max', value: 'generalv3.5' },
      { label: 'Spark Max-32K', value: 'max-32k' },
      { label: 'Spark4.0 Ultra', value: '4.0Ultra' },
    ],
  },
  {
    model: ProviderEnum.OLLAMA,
    name: 'Ollama',
    chatModels: [],
    embeddingModels: ['text2vec-bge-large-chinese:latest'],
  },
  {
    model: ProviderEnum.AZURE_OPENAI,
    name: 'Azure OpenAI',
    chatModels: ['gpt-3.5-turbo', 'gpt-4', 'gpt-4-32k', 'gpt-4-turbo', 'gpt-4o'],
    imageModels: ['dall-e-2', 'dall-e-3'],
  },
  {
    model: ProviderEnum.GEMINI,
    name: 'Gemini',
    chatModels: ['gemini-1.5-pro'],
  },
  {
    model: ProviderEnum.CLAUDE,
    name: 'Claude',
    chatModels: ['claude-3-opus', 'claude-3-opus-20240229', 'claude-3-sonnet', 'claude-3-haiku'],
  },
  {
    model: ProviderEnum.MIMO,
    name: '小米MiMo',
    chatModels: ['mimo-v2.5-pro'],
    imageModels: ['mimo-v2.5', 'mimo-v2-omni'],
  },
];

export const MODEL_TYPE_OPTIONS = [
  { value: 'CHAT', label: '聊天模型' },
  { value: 'EMBEDDING', label: '嵌入模型' },
  { value: 'IMAGE', label: '多模态模型' },
];
